Waiting for home GPS location to be set...
Home lat=47.6415, lon=-122.14, alt=122.151
Please click on PYGAME screen.
Episode 0+/3
Memory usage: 149108 (kb)
Starting...
Taking off...
Should now be flying...
Couldnt take depth pic.
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
Using TensorFlow backend.
Waiting for home GPS location to be set...
Home lat=47.6415, lon=-122.14, alt=122.158
Please click on PYGAME screen.
Episode 0+/3
Memory usage: 149124 (kb)
Starting...
Taking off...
Should now be flying...
Couldnt take depth pic.
Traceback (most recent call last):
  File "env_airsim.py", line 43, in <module>
    test_class()
  File "env_airsim.py", line 40, in test_class
    train_model(drone, agent, n_episodes, n_steps)
  File "/mnt/c/Users/vinic/Projects/arl/arl/support.py", line 56, in train_model
    env.moveToPosition(0,0,-10, 2, DrivetrainType.MaxDegreeOfFreedom, YawMode(False,0), 20, 1)
  File "/mnt/c/Users/vinic/Projects/arl/arl/PythonClient.py", line 86, in moveToPosition
    return self.client.call('moveToPosition',x, y, z, velocity, drivetrain, yaw_mode, lookahead, adaptive_lookahead)
  File "/home/vinicius/.local/lib/python3.5/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/vinicius/.local/lib/python3.5/site-packages/msgpackrpc/session.py", line 51, in send_request
    self._transport.send_message([message.REQUEST, msgid, method, args])
  File "/home/vinicius/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 94, in send_message
    sock.send_message(message, callback)
  File "/home/vinicius/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 19, in send_message
    self._stream.write(self._packer.pack(message), callback=callback)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
  File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
  File "msgpack/_packer.pyx", line 224, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3312)
  File "/home/vinicius/.local/lib/python3.5/site-packages/msgpackrpc/transport/tcp.py", line 12, in <lambda>
    self._packer = msgpack.Packer(encoding=encodings[0], default=lambda x: x.to_msgpack())
AttributeError: 'YawMode' object has no attribute 'to_msgpack'
